package l2e.gameserver.ai.model;

public enum CtrlEvent {
   EVT_THINK,
   EVT_ATTACKED,
   EVT_SPAWN,
   EVT_AGGRESSION,
   EVT_STUNNED,
   EVT_PARALYZED,
   EVT_SLEEPING,
   EVT_ROOTED,
   EVT_EVADED,
   EVT_READY_TO_ACT,
   EVT_USER_CMD,
   EVT_ARRIVED,
   EVT_ARRIVED_REVALIDATE,
   EVT_ARRIVED_BLOCKED,
   EVT_FORGET_OBJECT,
   EVT_CANCEL,
   EVT_DEAD,
   EVT_FAKE_DEATH,
   EVT_CONFUSED,
   EVT_MUTED,
   EVT_AFRAID,
   EVT_FINISH_CASTING,
   EVT_SEE_SPELL,
   EVT_BETRAYED,
   EVT_TIMER;
}
