package org.apache.commons.dbcp.cpdsadapter;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.apache.commons.dbcp.DelegatingConnection;
import org.apache.commons.dbcp.DelegatingPreparedStatement;

class ConnectionImpl extends DelegatingConnection {
   private final boolean accessToUnderlyingConnectionAllowed;
   private final PooledConnectionImpl pooledConnection;

   ConnectionImpl(PooledConnectionImpl pooledConnection, Connection connection, boolean accessToUnderlyingConnectionAllowed) {
      super(connection);
      this.pooledConnection = pooledConnection;
      this.accessToUnderlyingConnectionAllowed = accessToUnderlyingConnectionAllowed;
   }

   @Override
   public void close() throws SQLException {
      if (!this._closed) {
         this._closed = true;
         this.passivate();
         this.pooledConnection.notifyListeners();
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql));
      } catch (SQLException var3) {
         this.handleException(var3);
         return null;
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql, resultSetType, resultSetConcurrency));
      } catch (SQLException var5) {
         this.handleException(var5);
         return null;
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability));
      } catch (SQLException var6) {
         this.handleException(var6);
         return null;
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql, autoGeneratedKeys));
      } catch (SQLException var4) {
         this.handleException(var4);
         return null;
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql, columnIndexes));
      } catch (SQLException var4) {
         this.handleException(var4);
         return null;
      }
   }

   @Override
   public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
      this.checkOpen();

      try {
         return new DelegatingPreparedStatement(this, this.pooledConnection.prepareStatement(sql, columnNames));
      } catch (SQLException var4) {
         this.handleException(var4);
         return null;
      }
   }

   public boolean isAccessToUnderlyingConnectionAllowed() {
      return this.accessToUnderlyingConnectionAllowed;
   }

   @Override
   public Connection getDelegate() {
      return this.isAccessToUnderlyingConnectionAllowed() ? this.getDelegateInternal() : null;
   }

   @Override
   public Connection getInnermostDelegate() {
      return this.isAccessToUnderlyingConnectionAllowed() ? super.getInnermostDelegateInternal() : null;
   }
}
