package org.strixplatform.utils;

public enum ServerResponse {
   RESPONSE_OK,
   RESPONSE_FAILED_CLIENT_DATA_CHECKSUM_CHECK,
   RESPONSE_FAILED_CLIENT_HWID_CHECKSUM_CHECK,
   RESPONSE_FAILED_LICENSE_KEY_INFO_CHECK,
   RESPONSE_FAILED_CHECKSUM_CHECK,
   RESPONSE_FAILED_GAME_SESSION_CHECK,
   RESPONSE_FAILED_DETECTION_INFO_CHECK,
   RESPONSE_FAILED_LAUNCHED_STATE_CHECK,
   RESPONSE_FAILED_HWID_FULL_BLOCKED,
   RESPONSE_FAILED_HWID_BLOCK_BLOCKED,
   RESPONSE_FAILED_CLIENT_SIDE_VERSION_CHECK,
   RESPONSE_FAILED_ACTIVE_WINDOW_COUNT;
}
